-- ScholarHub database schema. Run in Supabase SQL Editor.
-- It includes a safe migration from the prior `municipaligitty` typo.

create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
insert into public.schools (name) values
  ('Cor Jesu College'), ('SC Padada'), ('Polytechnic'), ('UM Digos'),
  ('UM Bansalan'), ('Serapion'), ('SPAC'), ('ST Mary''s')
on conflict (name) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique, name text not null,
  first_name text, middle_name text, last_name text, phone text, sex text,
  birth_date date, purok text, barangay text, municipality text,
  school text references public.schools(name) on update cascade,
  year_level text, course text,
  scholar_type text check (scholar_type in ('Old scholar', 'New scholar')),
  role text not null default 'user' check (role in ('user', 'admin')),
  photo text, bio text,
  requirements_status text not null default 'Complete' check (requirements_status in ('Complete', 'Lacking')),
  scholar_status text not null default 'Active' check (scholar_status in ('Active', 'Non-active')),
  added_by_admin boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.profiles add column if not exists municipality text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
do $$ begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'profiles' and column_name = 'municipaligitty') then
    execute 'update public.profiles set municipality = coalesce(municipality, municipaligitty)';
  end if;
end $$;

create table if not exists public.scholarships (
  id bigint generated by default as identity primary key,
  title text not null, category text, description text, amount numeric(12,2) check (amount >= 0), deadline timestamptz,
  status text not null default 'Open' check (status in ('Draft', 'Open', 'Closed')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.requirements (
  id bigint generated by default as identity primary key,
  scholarship_id bigint not null references public.scholarships(id) on delete cascade,
  title text not null, description text, is_required boolean not null default true,
  created_at timestamptz not null default now(), unique(scholarship_id, title)
);
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  scholarship_id bigint not null references public.scholarships(id) on delete restrict,
  status text not null default 'Draft' check (status in ('Draft', 'Submitted', 'Under review', 'Approved', 'Rejected')),
  submitted_at timestamptz, reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz, reviewer_notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(student_id, scholarship_id)
);
create table if not exists public.application_requirements (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  requirement_id bigint not null references public.requirements(id) on delete cascade,
  file_path text, status text not null default 'Pending' check (status in ('Pending', 'Submitted', 'Accepted', 'Rejected')),
  reviewed_by uuid references public.profiles(id) on delete set null, reviewed_at timestamptz, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(application_id, requirement_id)
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete set null,
  message text not null check (char_length(message) <= 1000),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.announcement_reactions (
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reaction text not null check (reaction in ('like', 'heart')),
  created_at timestamptz not null default now(), primary key(announcement_id, user_id)
);
create table if not exists public.help_requests (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null check (char_length(subject) <= 100), message text not null check (char_length(message) <= 1000),
  status text not null default 'Pending' check (status in ('Pending', 'Resolved')),
  resolved_by uuid references public.profiles(id) on delete set null, resolved_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.announcements add column if not exists pinned boolean not null default false;
alter table public.help_requests add column if not exists admin_reply text check (char_length(admin_reply) <= 2000);
alter table public.help_requests add column if not exists replied_by uuid references public.profiles(id) on delete set null;
alter table public.help_requests add column if not exists replied_at timestamptz;
alter table public.help_requests add column if not exists archived_at timestamptz;
create table if not exists public.renewal_schedules (
  id bigint generated by default as identity primary key,
  school_name text not null unique references public.schools(name) on update cascade on delete cascade,
  deadline_at timestamptz, schedule_at timestamptz,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(), check (deadline_at is not null or schedule_at is not null)
);
create index if not exists applications_student_id_idx on public.applications(student_id);
create index if not exists applications_scholarship_id_idx on public.applications(scholarship_id);
create index if not exists help_requests_student_id_idx on public.help_requests(student_id);
create index if not exists help_requests_archived_at_idx on public.help_requests(archived_at);
create index if not exists requirements_scholarship_id_idx on public.requirements(scholarship_id);
create index if not exists app_req_application_id_idx on public.application_requirements(application_id);
create index if not exists app_req_requirement_id_idx on public.application_requirements(requirement_id);
create index if not exists reactions_user_id_idx on public.announcement_reactions(user_id);
create index if not exists announcements_author_id_idx on public.announcements(author_id);
create index if not exists scholarships_created_by_idx on public.scholarships(created_by);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id,email,name,first_name,middle_name,last_name,phone,sex,birth_date,purok,barangay,municipality,school,year_level,course,scholar_type)
  values (new.id,new.email,coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),new.raw_user_meta_data ->> 'first_name',new.raw_user_meta_data ->> 'middle_name',new.raw_user_meta_data ->> 'last_name',new.raw_user_meta_data ->> 'phone',new.raw_user_meta_data ->> 'sex',nullif(new.raw_user_meta_data ->> 'birth_date','')::date,new.raw_user_meta_data ->> 'purok',new.raw_user_meta_data ->> 'barangay',new.raw_user_meta_data ->> 'municipality',new.raw_user_meta_data ->> 'school',new.raw_user_meta_data ->> 'year_level',new.raw_user_meta_data ->> 'course',new.raw_user_meta_data ->> 'scholar_type');
  return new;
end $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;
create or replace function public.set_updated_at() returns trigger language plpgsql set search_path = public as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
do $$ declare tab text; begin
  foreach tab in array array['profiles','scholarships','applications','application_requirements','announcements','help_requests','renewal_schedules'] loop
    execute format('drop trigger if exists %I on public.%I', tab || '_set_updated_at', tab);
    execute format('create trigger %I before update on public.%I for each row execute procedure public.set_updated_at()', tab || '_set_updated_at', tab);
  end loop;
end $$;

alter table public.profiles enable row level security;
alter table public.schools enable row level security;
alter table public.scholarships enable row level security;
alter table public.requirements enable row level security;
alter table public.applications enable row level security;
alter table public.application_requirements enable row level security;
alter table public.announcements enable row level security;
alter table public.announcement_reactions enable row level security;
alter table public.help_requests enable row level security;
alter table public.renewal_schedules enable row level security;

-- Existing policies are replaced so this script can be safely re-run.
drop policy if exists "Profiles: own read" on public.profiles; drop policy if exists "Profiles: admin read" on public.profiles; drop policy if exists "Profiles: own update" on public.profiles; drop policy if exists "Profiles: admin manage" on public.profiles;
create policy "Profiles: own read" on public.profiles for select using (auth.uid() = id);
create policy "Profiles: admin read" on public.profiles for select using (public.is_admin());
create policy "Profiles: own update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id and role = 'user');
create policy "Profiles: admin manage" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Schools: read" on public.schools; drop policy if exists "Schools: admin manage" on public.schools;
create policy "Schools: read" on public.schools for select to authenticated using (true);
create policy "Schools: admin manage" on public.schools for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Scholarships: read" on public.scholarships; drop policy if exists "Scholarships: admin manage" on public.scholarships;
create policy "Scholarships: read" on public.scholarships for select to authenticated using (true);
create policy "Scholarships: admin manage" on public.scholarships for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Requirements: read" on public.requirements; drop policy if exists "Requirements: admin manage" on public.requirements;
create policy "Requirements: read" on public.requirements for select to authenticated using (true);
create policy "Requirements: admin manage" on public.requirements for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Applications: student read" on public.applications; drop policy if exists "Applications: student create" on public.applications; drop policy if exists "Applications: student update" on public.applications; drop policy if exists "Applications: admin manage" on public.applications;
create policy "Applications: student read" on public.applications for select using (student_id = auth.uid());
create policy "Applications: student create" on public.applications for insert with check (student_id = auth.uid());
create policy "Applications: student update" on public.applications for update using (student_id = auth.uid() and status in ('Draft','Submitted')) with check (student_id = auth.uid());
create policy "Applications: admin manage" on public.applications for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Application requirements: student read" on public.application_requirements; drop policy if exists "Application requirements: student create" on public.application_requirements; drop policy if exists "Application requirements: student update" on public.application_requirements; drop policy if exists "Application requirements: admin manage" on public.application_requirements;
create policy "Application requirements: student read" on public.application_requirements for select using (exists (select 1 from public.applications a where a.id = application_id and a.student_id = auth.uid()));
create policy "Application requirements: student create" on public.application_requirements for insert with check (exists (select 1 from public.applications a where a.id = application_id and a.student_id = auth.uid()));
create policy "Application requirements: student update" on public.application_requirements for update using (exists (select 1 from public.applications a where a.id = application_id and a.student_id = auth.uid())) with check (exists (select 1 from public.applications a where a.id = application_id and a.student_id = auth.uid()));
create policy "Application requirements: admin manage" on public.application_requirements for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Announcements: read" on public.announcements; drop policy if exists "Announcements: admin manage" on public.announcements;
create policy "Announcements: read" on public.announcements for select to authenticated using (true);
create policy "Announcements: admin manage" on public.announcements for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Reactions: read" on public.announcement_reactions; drop policy if exists "Reactions: own read" on public.announcement_reactions; drop policy if exists "Reactions: own create" on public.announcement_reactions; drop policy if exists "Reactions: own update" on public.announcement_reactions; drop policy if exists "Reactions: own delete" on public.announcement_reactions;
create policy "Reactions: read" on public.announcement_reactions for select to authenticated using (true);
create policy "Reactions: own create" on public.announcement_reactions for insert with check (user_id = auth.uid());
create policy "Reactions: own update" on public.announcement_reactions for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Reactions: own delete" on public.announcement_reactions for delete using (user_id = auth.uid());
drop policy if exists "Help requests: student read" on public.help_requests; drop policy if exists "Help requests: student create" on public.help_requests; drop policy if exists "Help requests: admin manage" on public.help_requests;
create policy "Help requests: student read" on public.help_requests for select using (student_id = auth.uid());
create policy "Help requests: student create" on public.help_requests for insert with check (student_id = auth.uid());
create policy "Help requests: admin manage" on public.help_requests for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Renewal schedules: read" on public.renewal_schedules; drop policy if exists "Renewal schedules: admin manage" on public.renewal_schedules;
create policy "Renewal schedules: read" on public.renewal_schedules for select to authenticated using (true);
create policy "Renewal schedules: admin manage" on public.renewal_schedules for all using (public.is_admin()) with check (public.is_admin());

-- Create a private `application-files` bucket in Supabase Storage for requirement uploads.
-- After registering the first administrator: update public.profiles set role = 'admin' where email = 'admin@gmail.com';
