-- Migration: 20260912_renewal_documents_and_replies.sql
-- Enhances ScholarHub schema with Renewal Documents tracking, auto-sync triggers, and Help Ticket replies.

-- 1. Renewal Documents Table
create table if not exists public.renewal_documents (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  document_type text not null check (document_type in ('COG', 'COR', 'Student ID', 'Barangay Clearance')),
  academic_year text not null default '2026-2027',
  semester text not null default '1st Semester' check (semester in ('1st Semester', '2nd Semester', 'Summer')),
  file_url text not null,
  file_name text not null,
  file_size bigint,
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  reviewer_id uuid references public.profiles(id) on delete set null,
  reviewer_notes text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, document_type, academic_year, semester)
);

create index if not exists renewal_docs_student_idx on public.renewal_documents(student_id);
create index if not exists renewal_docs_status_idx on public.renewal_documents(status);

-- 2. Enhance Help Requests with Admin Reply columns
alter table public.help_requests add column if not exists admin_reply text;
alter table public.help_requests add column if not exists reply_at timestamptz;
alter table public.help_requests add column if not exists replied_by uuid references public.profiles(id) on delete set null;

-- 3. Trigger for updated_at
drop trigger if exists renewal_documents_set_updated_at on public.renewal_documents;
create trigger renewal_documents_set_updated_at before update on public.renewal_documents for each row execute procedure public.set_updated_at();

-- 4. Automated Status Synchronization Trigger
-- When all 4 documents are Approved, profiles.requirements_status is set to 'Complete'.
-- Otherwise, if any document is missing, pending, or rejected, it is set to 'Lacking'.
create or replace function public.sync_student_renewal_status() returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_approved_count int;
  v_student_id uuid;
begin
  v_student_id := coalesce(new.student_id, old.student_id);
  
  select count(*) into v_approved_count
  from public.renewal_documents
  where student_id = v_student_id
    and academic_year = coalesce(new.academic_year, old.academic_year, '2026-2027')
    and semester = coalesce(new.semester, old.semester, '1st Semester')
    and status = 'Approved';

  if v_approved_count >= 4 then
    update public.profiles
    set requirements_status = 'Complete', updated_at = now()
    where id = v_student_id;
  else
    update public.profiles
    set requirements_status = 'Lacking', updated_at = now()
    where id = v_student_id;
  end if;

  return new;
end $$;

drop trigger if exists on_renewal_document_changed on public.renewal_documents;
create trigger on_renewal_document_changed
after insert or update or delete on public.renewal_documents
for each row execute procedure public.sync_student_renewal_status();

-- 5. Row Level Security (RLS)
alter table public.renewal_documents enable row level security;

drop policy if exists "Renewal docs: student read own" on public.renewal_documents;
create policy "Renewal docs: student read own" on public.renewal_documents
  for select using (student_id = auth.uid());

drop policy if exists "Renewal docs: student insert own" on public.renewal_documents;
create policy "Renewal docs: student insert own" on public.renewal_documents
  for insert with check (student_id = auth.uid());

drop policy if exists "Renewal docs: student update own" on public.renewal_documents;
create policy "Renewal docs: student update own" on public.renewal_documents
  for update using (student_id = auth.uid() and status in ('Pending', 'Rejected'))
  with check (student_id = auth.uid());

drop policy if exists "Renewal docs: admin manage all" on public.renewal_documents;
create policy "Renewal docs: admin manage all" on public.renewal_documents
  for all using (public.is_admin()) with check (public.is_admin());

-- 6. Storage Bucket & Policies (Run in Supabase Storage setup)
insert into storage.buckets (id, name, public)
values ('renewal-documents', 'renewal-documents', false)
on conflict (id) do nothing;

drop policy if exists "Renewal docs: student upload" on storage.objects;
create policy "Renewal docs: student upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'renewal-documents' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Renewal docs: student read own" on storage.objects;
create policy "Renewal docs: student read own" on storage.objects
  for select to authenticated
  using (bucket_id = 'renewal-documents' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));

drop policy if exists "Renewal docs: admin all" on storage.objects;
create policy "Renewal docs: admin all" on storage.objects
  for all to authenticated
  using (bucket_id = 'renewal-documents' and public.is_admin());
